### ISSUE TITLE
Introduce undo redo

### ISSUE THREAD

**Issue by danielabar** [CANVE/canve-viz#14]
Starting with a simple implementation where only most recent undone action can be redone.

**Comment by matanox** [comment]
Tech spec suggestion draft: https://github.com/CANVE/visualizer/issues/10

**Comment by matanox** [comment]
Per technical research this should use the native [html5 history api](https://developer.mozilla.org/en-US/docs/Web/API/History_API), which is the way back/forward is managed nowadays. Have to note the object's size limitation mentioned there on MDN (640k characters? only in firefox?) means need to consider whether to keep the graph in the object, a delta, or a pointer to a copy of a data saved elsewhere. A medium size graph took 0.5M last I checked, so 640K is a bit marginal.....

**Comment by matanox** [comment]
http://aurelia.io/docs.html#configuring-push-state might be probably necessary so that this plays well with Aurelia's browser history management as per its routing.

**Comment by matanox** [comment]
From the gitter:

> Not sure what difficulty the guy faced in the interview myself.. but redux currently comes with an undo [reference implementation](http://rackt.github.io/redux/docs/recipes/ImplementingUndoHistory.html) and a ["plugin"](https://github.com/omnidan/redux-undo) that claims to provide that implementation. The first link is an undo 101. It might be useful for only the undo/redo part; the integration into the existing framework would probably just be fetching/pushing anything that needs to be part of "redo/undo state" to redux, then binding the results as usual in Aurelia. I'll paste this in the undo/redo ticket for reference...
> Basically this is all more of a design pattern... but maybe something in redux makes it simpler than rolling the design pattern.

Redux architecture seems to be simple - [`actions`](http://rackt.github.io/redux/docs/basics/Actions.html) only act like orders (this is called messages in other frameworks like Akka) and [`reducers`](http://rackt.github.io/redux/docs/basics/Reducers.html) define what actually needs to be done for each message. 

Then it optionally provides [workflow for asynchronous state manipulation](http://rackt.github.io/redux/docs/advanced/AsyncActions.html), and middleware (which really is only useful for debug or logging, it's like node.js middleware, not that exciting..).

**Comment by matanox** [comment]
I'd consider the latter mainly on the merits of how much its testing best practice is inline with Aurelia's or just sensible to follow. Otherwise the quite identical design on the original ticket in the legacy repo can still be manually done.

**Comment by danielabar** [comment]
[Javascript-undo-manager](https://github.com/ArthurClemens/Javascript-Undo-Manager) may be helpful, seems to be framework agnostic

Will need to implement "remove" versions of the functions in [graph-modifier](https://github.com/CANVE/canve-viz/blob/master/src%2Fgraph%2Fgraph-modifier.js)

**Comment by matanox** [comment]
https://github.com/ArthurClemens/Javascript-Undo-Manager looks good as
well. I'd look some more on its test code but looks like it has basic
testing in place.
