### ISSUE TITLE
Highlight edges

### ISSUE THREAD

**Issue by danielabar** [CANVE/canve-viz#48]
Legacy app had a feature where selecting (or merely hovering?) over a node would highlight all its edges. This is very useful, especially as graph size increases.

Also not all of the edge styling from legacy was ported over, in the form of `edge-style.js`, take this opportunity to bring this over. Also consider on edge hover should show `edgeKind` maybe as a tooltip.

**Comment by matanox** [comment]
Let me know if you need help zooming on the code that does that in legacy...
